### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by syedalamabbas** [NullP0inter/UE4_Boost#1]
Hi, 
         I tried to use this project on my machine. It is windows 10 with visual studio 2017. But I get the following error. Any ideas on how to resolve these ?

`2>Performing 3 actions (4 in parallel)
2>BoostTestFunctionLibrary.cpp
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/config/stdlib/dinkumware.hpp(99): warning C4668: '_HAS_NAMESPACE' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/throw_exception.hpp(3): warning C4668: '__GNUC__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/throw_exception.hpp(3): warning C4668: '__GNUC_MINOR__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/tuple/detail/tuple_basic.hpp(44): warning C4668: 'BOOST_GCC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/tuple/detail/tuple_basic.hpp(982): warning C4668: 'BOOST_GCC' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(16): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(16): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(20): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(20): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(36): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(36): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(50): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_default_constructible.hpp(50): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_constructible.hpp(15): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_constructible.hpp(15): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_copy_constructible.hpp(15): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/type_traits/is_copy_constructible.hpp(15): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/predef/other/endian.h(151): warning C4668: 'BOOST_ARCH_AMD64' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/smart_ptr/shared_ptr.hpp(801): warning C4668: '__GNUC__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/config/abi_prefix.hpp(19): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/archive/detail/abi_prefix.hpp(11): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/archive/archive_exception.hpp(34): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/config/abi_suffix.hpp(20): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/archive/detail/abi_suffix.hpp(14): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/archive/archive_exception.hpp(98): error C4103: alignment changed after including header, may be due to missing #pragma pack(pop)
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/mpl/aux_/config/operators.hpp(27): warning C4668: '__NVCC___WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/mpl/aux_/config/operators.hpp(27): warning C4668: '__NVCC__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/optional/detail/optional_config.hpp(99): warning C4668: 'BOOST_GCC_VERSION_WORKAROUND_GUARD' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>F:\UE4_Boost\ThirdParty\BoostInternalLibrary\includes\boost/optional/detail/optional_config.hpp(99): warning C4668: 'BOOST_GCC_VERSION' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
2>ERROR : UBT error : Failed to produce item: F:\UE4_Boost\Binaries\Win64\UE4Editor-UE4_Boost.dll
2>Total build time: 8.30 seconds (Local executor: 0.00 seconds)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command "D:\GitHub\UnrealEngine\Engine\Build\BatchFiles\Build.bat UE4_BoostEditor Win64 Development "F:\UE4_Boost\UE4_Boost.uproject" -waitmutex" exited with code 5. Please verify that you have sufficient rights to run this command.
2>Done building project "UE4_Boost.vcxproj" -- FAILED.`

**Comment by syedalamabbas** [comment]
I found a solution: in user.hpp just enable this line of code - 

`// BOOST_DISABLE_ABI_HEADERS: Stops boost headers from including any 
// prefix/suffix headers that normally control things like struct 
// packing and alignment. 
#define BOOST_DISABLE_ABI_HEADERS`

**Comment by mjedmonds** [comment]
For anyone stumbling upon this, edit `BoostInternalLibrary/includes/boost/config/user.hpp`:

```c++
// BOOST_DISABLE_ABI_HEADERS: Stops boost headers from including any 
// prefix/suffix headers that normally control things like struct 
// packing and alignment. 
#define BOOST_DISABLE_ABI_HEADERS
```

Then use the following `THIRD_PARTY_INCLUDES_XXX` marco guards when you include from the library in your header:

```c++
THIRD_PARTY_INCLUDES_START
#include <boost/graph/adjacency_list.hpp>
THIRD_PARTY_INCLUDES_END
```

This works with Boost 1.72 and UE4 4.20.

**Comment by acxsasx** [comment]
> 
> 
> For anyone stumbling upon this, edit `BoostInternalLibrary/includes/boost/config/user.hpp`:
> 
> ```c++
> // BOOST_DISABLE_ABI_HEADERS: Stops boost headers from including any 
> // prefix/suffix headers that normally control things like struct 
> // packing and alignment. 
> #define BOOST_DISABLE_ABI_HEADERS
> ```
> 
> Then use the following `THIRD_PARTY_INCLUDES_XXX` marco guards when you include from the library in your header:
> 
> ```c++
> THIRD_PARTY_INCLUDES_START
> #include <boost/graph/adjacency_list.hpp>
> THIRD_PARTY_INCLUDES_END
> ```
> 
> This works with Boost 1.72 and UE4 4.20.
Thank you.
Got it to compile with 4.24.3.

**Comment by clarkjacob4** [comment]
> For anyone stumbling upon this, edit `BoostInternalLibrary/includes/boost/config/user.hpp`:
> 
> ```c++
> // BOOST_DISABLE_ABI_HEADERS: Stops boost headers from including any 
> // prefix/suffix headers that normally control things like struct 
> // packing and alignment. 
> #define BOOST_DISABLE_ABI_HEADERS
> ```
> 
> Then use the following `THIRD_PARTY_INCLUDES_XXX` marco guards when you include from the library in your header:
> 
> ```c++
> THIRD_PARTY_INCLUDES_START
> #include <boost/graph/adjacency_list.hpp>
> THIRD_PARTY_INCLUDES_END
> ```
> 
> This works with Boost 1.72 and UE4 4.20.

Works with Boost 1.78.0 and UE4 4.27.2, however I recommend adding this line under the project Build.cs file instead of editing the user.hpp file;

`PublicDefinitions.Add("BOOST_DISABLE_ABI_HEADERS=1");`
